language: go
go:
  - 1.8.x
install:
  - wget https://github.com/google/protobuf/releases/download/v3.4.0/protoc-3.4.0-linux-x86_64.zip
  - unzip protoc-3.4.0-linux-x86_64.zip -d /usr/local
  - sudo add-apt-repository -y ppa:masterminds/glide && sudo apt-get update
  - sudo apt-get install -y glide