language: go
go:
  - 1.8.x
install:
  - wget https://github.com/google/protobuf/archive/v3.4.0.tar.gz
  - tar -xzvf v3.4.0.tar.gz
  - pushd protobuf-3.4.0 && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install && popd
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
  - sudo apt-get install glide