language: go
go:
  - 1.8.x
install:
  - wget https://github.com/google/protobuf/archive/v3.4.0.tar.gz
  - tar -xzvf v3.4.0.tar.gz
  - pushd v3.4.0 && ./configure --prefix=/usr && make && sudo make install && popd